### ISSUE TITLE
Reqest extras

### ISSUE THREAD

**Issue by lucaegli** [gosow9/pmod#2]
# Requested changes flag manager
1. Path in configfile for loading destination and saving
2. Default preflag values on False
3. Bug Preflag selection 
4. Pick event radius bigger
5. Config file "CalL01" for header in files and folder structure
6. Batch file for running program on click

**Comment by gosow9** [comment]
Splitting up Request into different issues 
- [ ] Path in configfile for loading destination and saving
- [x] Default preflag values on False
- [x] Bug Preflag selection
- [x] Pick event radius bigger
- [ ] Config file "CalL01" for header in files and folder structure
- [ ] Batch file for running program on click

**Comment by lucaegli** [comment]
Additional request:
1. Include button for autoflagging on/off (if autoflagging is ready for operational use)
